site_name: Tritan
theme:
  name: material
  custom_dir: 'theme'
  palette:
    primary: blue
    accent: blue
  favicon: 'img/favicon.ico'
  logo:
    icon: 'account_balance'
repo_name: 'tapanther/Tritan'
repo_url: 'https://github.com/tapanther/Tritan'

nav:
  - Home: 'index.md'
  - General:
      - Timeline : 'timeline.md'
  - MajorPowers:
      - Republic of Siddarmark : 'Republic.md'
      - Kingdom of Dohlar : 'Blackpoint.md'
  - NPC:
      - Lyhl Habborhlyn : 'Lyhl_Habborlyn.md'
  - Settlements:
      - Siddar City : 'SiddarCity.md'
      - Blackpoint (City) : 'BlackpointCity.md'
