
site_name: Tritan
theme:
  name: material
  custom_dir: 'yaml-wiki/theme'
  palette:
    primary: blue
    accent: blue
  favicon: 'img/favicon.ico'
  logo:
    icon: 'account_balance'
repo_name: 'tapanther/Tritan'
repo_url: 'https://github.com/tapanther/Tritan'
site_url: 'https://tapanther.github.io/Tritan/'

  
extra_css:
  - stylesheets_lib/uml.css
  
extra_javascript:
  - js_lib/uml.js
  - js_lib/mermaid.min.js
#  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.4.6/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.3.0/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.9.1/underscore-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.13.0/flowchart.min.js

markdown_extensions:
  - admonition
  - pymdownx.superfences :
      custom_fences :
        - name : flow
          class : uml-flowchart
          format : !!python/name:pymdownx.superfences.fence_div_format
        - name : sequence
          class : uml-sequence-diagram
          format : !!python/name:pymdownx.superfences.fence_div_format
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

nav:
  - Home : index.md
  - Campaign :
    - Current Party Makeup : CurrentParty.md
    - Logs :
      - Act 0 - The Alchemist's Tomb : CampaignLog_0.md
      - Act 1 - The Ravenous Horde : CampaignLog_1.md
      - Act 2 - The Emerald Tablets : CampaignLog_2.md
  - General :
    - Alchemist's Journal : AlchemistJournal.md
    - Book of Prophesy : Prophesy.md
    - Gnolls : Gnolls.md
    - Timeline : Timeline.md
    - Tritanian Calendar : Calendar.md
  - History :
    - Religion in Tritan : Religion.md
    - Stonhyr's Speech at Noxwall : StonhyrNoxwallSpeech.md
  - Locations :
    - Nonewallow : Nonewallow.md
    - First Age Ruins :
      - Broken Gate : Gate.md
      - Leadenport : Leadenport.md
      - Terraworth : Terraworth.md
  - Major Powers :
    - Kingdom of Dohlar :
      - Kingdom of Dohlar : Dohlar.md
    - Republic of Siddarmark :
      - Republic of Siddarmark : Republic.md
      - Government :
        - Gendarmerie of Siddar City : GendarmerieSiddar.md
        - High Court of Inquiry : HighCourtOfInquiry.md
        - Lord Protector of the Republic : LordProtector.md
        - Republic Expeditionary Forces : REF.md
  - NPC :
    - Azoth the Wise : Azoth.md
    - Baltatrax the Ravager : Baltatrax.md
    - Faelix : Faelix.md
    - Uþer : UtherNPC.md
    - Blackpoint :
      - Nyhlus Verriskrit : NyhlusVerriskrit.md
    - Cult of the Eternal Flame :
      - Pleas Morgan : PleasMorgan.md
    - Ravenhelm :
      - Jacques Manget : JacquesManget.md
    - Republic :
      - Arthyr Borthwell : ArthyrBorthwell.md
      - Greghor Stonhyr : GreghorStonhyr.md
      - Leighya Enryht : LeighyaEnryht.md
      - Lyhl Habborhlyn : LyhlHabborlyn.md
  - Organization :
    - Cult of Five : CultOfFive.md
    - Mother Church (Religion) : MotherChurch.md
    - Republic :
      - Gahrdynyr Trade House : GahrdynyrTradeHouse.md
    - Villains :
      - Eternal Flame Cult : EternalFlameCult.md
  - Settlements :
    - Kingdom of Dohlar :
      - Blackpoint : Blackpoint.md
    - Republic :
      - Cantfall : Cantfall.md
      - Glacierheart : Glacierheart.md
      - Noxwall : Noxwall.md
      - Ravenhelm : Ravenhelm.md
      - Siddar City : SiddarCity.md
      - Tallowburn : Tallowburn.md
  - Categories :
      - Campaign : Campaign.md
      - General : General.md
      - History : History.md
      - Locations : Locations.md
      - Major Powers : Major Powers.md
      - NPC : NPC.md
      - Organization : Organization.md
      - Settlements : Settlements.md
