site_name: Tritan
theme:
  name: material
  custom_dir: 'theme'
  palette:
    primary: blue
    accent: blue
    icon: 'book'
repo_name: 'tapanther/Tritan'
repo_url: 'https://github.com/tapanther/Tritan'

nav:
  - Home: 'index.md'
  - MajorPowers:
      - Kingdom of Dohlar : 'Blackpoint.md'
      - Republic of Siddarmark : 'Republic.md'
  - Settlements:
      - Blackpoint (City) : 'BlackpointCity.md'
      - Siddar City : 'SiddarCity.md'
