site_name: Tritan
theme:
  name: material
  custom_dir: 'theme'
  palette:
    primary: blue
    accent: blue
  favicon: 'img/favicon.ico'
  logo:
    icon: 'account_balance'
repo_name: 'tapanther/Tritan'
repo_url: 'https://github.com/tapanther/Tritan'
site_url: 'https://tapanther.github.io/Tritan/Prophesy/'

extra:
  disqus: 'tritan'

markdown_extensions:
  - admonition

nav:
  - Home: 'index.md'
  - Campaign:
      - 'Act 1 - The Ravenous Horde' : 'CampaignLog_1.md'
  - General:
      - 'Tritanian Calendar' : 'Calendar.md'
      - 'Book of Prophesy' : 'Prophesy.md'
      - 'Stonhyr&#39;s Speech at Noxwall' : 'StonhyrNoxwallSpeech.md'
      - 'Timeline' : 'Timeline.md'
  - MajorPowers:
      - 'Kingdom of Dohlar' : 'Blackpoint.md'
      - 'Republic of Siddarmark' : 'Republic.md'
  - NPC:
      - 'Greghor Stonhyr' : 'GreghorStonhyr.md'
      - 'Lyhl Habborhlyn' : 'Lyhl_Habborlyn.md'
  - Organization:
      - 'Gahrdynyr Trade House' : 'GahrdynyrTradeHouse.md'
  - Settlements:
      - 'Blackpoint (City)' : 'BlackpointCity.md'
      - 'Siddar City' : 'SiddarCity.md'
