site_name: Tritan
theme:
  name: material
  custom_dir: 'theme'
  palette:
    primary: blue
    accent: blue
  favicon: 'img/favicon.ico'
  logo:
    icon: 'account_balance'
repo_name: 'tapanther/Tritan'
repo_url: 'https://github.com/tapanther/Tritan'
site_url: 'https://tapanther.github.io/Tritan/Prophesy/'

extra:
  disqus: 'tritan'

nav:
  - Home: 'index.md'
  - General:
      - Book of Prophesy : 'Prophesy.md'
      - Stonhyr's Speech at Noxwall : 'StonhyrNoxwallSpeech.md'
      - Timeline : 'timeline.md'
  - MajorPowers:
      - Kingdom of Dohlar : 'Blackpoint.md'
      - Republic of Siddarmark : 'Republic.md'
  - NPC:
      - Greghor Stonhyr : 'GreghorStonhyr.md'
      - Lyhl Habborhlyn : 'Lyhl_Habborlyn.md'
  - Organization:
      - Gahrdynyr Trade House : 'GahrdynyrTradeHouse.md'
  - Settlements:
      - Blackpoint (City) : 'BlackpointCity.md'
      - Siddar City : 'SiddarCity.md'
