site_name: Tritan
theme:
  name: material
  custom_dir: 'theme'
  palette:
    primary: blue
    accent: blue
  favicon: 'img/favicon.ico'
  logo:
    icon: 'account_balance'
repo_name: 'tapanther/Tritan'
repo_url: 'https://github.com/tapanther/Tritan'
site_url: 'https://tapanther.github.io/Tritan/Prophesy/'

extra:
  disqus: 'tritan'

markdown_extensions:
  - admonition

nav:
  - Home: 'index.md'
  - Campaign:
      - 'Act 0 - The Alchemist&#39;s Tomb' : 'CampaignLog_0.md'
      - 'Act 1 - The Ravenous Horde' : 'CampaignLog_1.md'
  - General:
      - 'Alchemist&#39;s Journal' : 'AlchemistJournal.md'
      - 'Book of Prophesy' : 'Prophesy.md'
      - 'Gnolls' : 'Gnolls.md'
      - 'Stonhyr&#39;s Speech at Noxwall' : 'StonhyrNoxwallSpeech.md'
      - 'Timeline' : 'Timeline.md'
      - 'Tritanian Calendar' : 'Calendar.md'
  - History:
      - 'Religion in Tritan' : 'Religion.md'
  - Locations:
      - 'Nonewallow' : 'Nonewallow.md'
  - Major Powers:
      - 'Kingdom of Dohlar' : 'Dohlar.md'
      - 'Republic of Siddarmark' : 'Republic.md'
  - NPC:
      - 'Azoth the Wise' : 'Azoth.md'
      - 'Faelix' : 'Faelix.md'
      - 'Greghor Stonhyr' : 'GreghorStonhyr.md'
      - 'Lyhl Habborhlyn' : 'Lyhl_Habborlyn.md'
  - Organization:
      - 'Cult of Five' : 'CultOfFive.md'
      - 'Gahrdynyr Trade House' : 'GahrdynyrTradeHouse.md'
      - 'Mother Church (Religion)' : 'MotherChurch.md'
      - 'Republic Expeditionary Forces' : 'REF.md'
  - Settlements:
      - 'Blackpoint' : 'Blackpoint.md'
      - 'Cantfall' : 'Cantfall.md'
      - 'Noxwall' : 'Noxwall.md'
      - 'Siddar City' : 'SiddarCity.md'
