
site_name: Tritan
theme:
  name: material
  custom_dir: 'yaml-wiki/theme'
  palette:
    primary: blue
    accent: blue
  favicon: 'img/favicon.ico'
  icon:
    logo: 'material/bank'
repo_name: 'tapanther/Tritan'
repo_url: 'https://github.com/tapanther/Tritan'
site_url: 'https://tapanther.github.io/Tritan/'

extra:
    disqus: 'tritan'





markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences :
      custom_fences :
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home : index.md
  - Campaign :
    - Current Party Makeup : CurrentParty.md
    - Logs :
      - Act 0 - The Alchemist's Tomb : CampaignLog_0.md
      - Act 1 - The Ravenous Horde : CampaignLog_1.md
      - Act 2 - The Emerald Tablets : CampaignLog_2.md
  - General :
    - Alchemist's Journal : AlchemistJournal.md
    - Book of Prophesy : Prophesy.md
    - Gnolls : Gnolls.md
    - Stonhyr's Ultimatum to Dohlar : UltimatumToDohlar.md
    - Timeline : Timeline.md
    - Tritanian Calendar : Calendar.md
  - History :
    - Religion in Tritan : Religion.md
    - Stonhyr's Speech at Noxwall : StonhyrNoxwallSpeech.md
  - Locations :
    - Nonewallow : Nonewallow.md
    - First Age Ruins :
      - Ashmourne : Ashmourne.md
      - Broken Gate : Gate.md
      - Leadenport : Leadenport.md
      - Terraworth : Terraworth.md
  - Major Powers :
    - Kingdom of Dohlar :
      - Kingdom of Dohlar : Dohlar.md
    - Republic of Siddarmark :
      - Republic of Siddarmark : Republic.md
      - Government :
        - Gendarmerie of Siddar City : GendarmerieSiddar.md
        - High Court of Inquiry : HighCourtOfInquiry.md
        - Lord Protector of the Republic : LordProtector.md
        - Republic Expeditionary Forces : REF.md
  - Minor Powers :
    - Empire of the Rufous Wings : RufousWings.md
    - Cult of the Eternal Flame :
      - Cult of the Eternal Flame : EternalFlameCult.md
      - Dusk Templar Order : DuskTemplar.md
  - NPC :
    - Azoth the Wise : Azoth.md
    - Baltatrax the Ravager : Baltatrax.md
    - Cyton the Learned : Cyton.md
    - Elandorr Krutoq : ElandorrKrutoq.md
    - Faelix : Faelix.md
    - Othes : Othes.md
    - Uþer : UtherNPC.md
    - Cult of the Eternal Flame :
      - Nyhlus Verriskrit : NyhlusVerriskrit.md
      - Pleas Morgan : PleasMorgan.md
      - Tyar Besir : TyarBesir.md
    - Kingdom of Dohlar :
      - Nell Reynfred : NellReynfred.md
      - Yrvyn Lynch : YrvynLynch.md
    - Ravenhelm :
      - Jacques Manget : JacquesManget.md
    - Republic :
      - Ahrys Tohmys : AhrynTohmys.md
      - Arthyr Borthwell : ArthyrBorthwell.md
      - Greghor Stonhyr : GreghorStonhyr.md
      - Leighya Enryht : LeighyaEnryht.md
      - Lyhl Habborhlyn : LyhlHabborlyn.md
      - Tohazar Nammesarian : Tohazar.md
  - Organization :
    - Cult of Five : CultOfFive.md
    - Mother Church (Religion) : MotherChurch.md
    - Republic :
      - Gahrdynyr Trade House : GahrdynyrTradeHouse.md
  - Settlements :
    - Kingdom of Dohlar :
      - Blackpoint : Blackpoint.md
    - Republic :
      - Cantfall : Cantfall.md
      - Glacierheart : Glacierheart.md
      - Noxwall : Noxwall.md
      - Ravenhelm : Ravenhelm.md
      - Siddar City : SiddarCity.md
      - Tallowburn : Tallowburn.md
  - Categories :
      - Campaign : Campaign.md
      - General : General.md
      - History : History.md
      - Locations : Locations.md
      - Major Powers : Major Powers.md
      - Minor Powers : Minor Powers.md
      - NPC : NPC.md
      - Organization : Organization.md
      - Settlements : Settlements.md
