site_name: Tritan
theme:
  name: material
  custom_dir: 'theme'
  palette:
    primary: blue
    accent: blue
  favicon: 'img/favicon.ico'
  logo:
    icon: 'account_balance'
repo_name: 'tapanther/Tritan'
repo_url: 'https://github.com/tapanther/Tritan'
site_url: 'https://tapanther.github.io/Tritan/Prophesy/'

extra:
  disqus: 'tritan'

markdown_extensions:
  - admonition

nav:
  - Home: 'index.md'
{% for category, data in navStruct|dictsort %}
  - {{ category }}:
{% for item in data|sort(attribute='title') %}
      - '{{ item.title | e }}' : '{{ item.file }}'
{% endfor %}
{% endfor %}
